# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'previewData-Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'OrkaPreviewData', path: '../'

  # Pods for previewData-Demo

  target 'previewData-DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'previewData-DemoUITests' do
    # Pods for testing
  end
end
